/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package billing_system.applicationUIs;

import billing_system.models.ComponentDetails;
import billing_system.dboperation.DBOperations;
import javax.swing.JOptionPane;

/**
 *
 * @author ASHAN
 */
public class AddDetails extends javax.swing.JFrame {
    
    DBOperations dbo = new DBOperations();

    /**
     * Creates new form AddDetails
     */
    public AddDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_AddDetails = new javax.swing.JPanel();
        l_ProductName = new javax.swing.JLabel();
        txt_ProductName = new javax.swing.JTextField();
        l_UnitPrice = new javax.swing.JLabel();
        txt_UnitPrice = new javax.swing.JTextField();
        l_ProductName2 = new javax.swing.JLabel();
        txt_Quantity = new javax.swing.JTextField();
        txt_Total = new javax.swing.JTextField();
        l_Total = new javax.swing.JLabel();
        btn_Checkin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp_AddDetails.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter Component Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N

        l_ProductName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l_ProductName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_ProductName.setText("Product Name");

        txt_ProductName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        l_UnitPrice.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l_UnitPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_UnitPrice.setText("Unit Price");

        txt_UnitPrice.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        l_ProductName2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l_ProductName2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_ProductName2.setText("Quantity");

        txt_Quantity.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txt_Total.setEditable(false);
        txt_Total.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        l_Total.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l_Total.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_Total.setText("Total");

        btn_Checkin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_Checkin.setText("Check In");
        btn_Checkin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CheckinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_AddDetailsLayout = new javax.swing.GroupLayout(jp_AddDetails);
        jp_AddDetails.setLayout(jp_AddDetailsLayout);
        jp_AddDetailsLayout.setHorizontalGroup(
            jp_AddDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_AddDetailsLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jp_AddDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_AddDetailsLayout.createSequentialGroup()
                        .addComponent(l_ProductName2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_AddDetailsLayout.createSequentialGroup()
                        .addComponent(l_UnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_UnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_AddDetailsLayout.createSequentialGroup()
                        .addComponent(l_ProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_ProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_AddDetailsLayout.createSequentialGroup()
                        .addComponent(l_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jp_AddDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Checkin, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jp_AddDetailsLayout.setVerticalGroup(
            jp_AddDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_AddDetailsLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jp_AddDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_ProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_AddDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_UnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_UnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_AddDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_ProductName2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_AddDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btn_Checkin, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(229, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp_AddDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp_AddDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CheckinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CheckinActionPerformed
        ComponentDetails cdtl =new ComponentDetails();
        //wrap data to the ComponentDetails class
        cdtl.setProductId(0);
        cdtl.setProductName(txt_ProductName.getText());
        double unitprice = new Double(txt_UnitPrice.getText()).doubleValue();
        cdtl.setUnitPrice(unitprice);
        double quantity = new Double(txt_Quantity.getText()).doubleValue();
        cdtl.setQuantity(quantity);
        cdtl.setTotal(unitprice*quantity);
        
        if(dbo.addComponentDetails(cdtl)){
            JOptionPane.showMessageDialog(this, "successfully inserted");
        }else{
            JOptionPane.showMessageDialog(this, "Error");
        }
        
    }//GEN-LAST:event_btn_CheckinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Checkin;
    private javax.swing.JPanel jp_AddDetails;
    private javax.swing.JLabel l_ProductName;
    private javax.swing.JLabel l_ProductName2;
    private javax.swing.JLabel l_Total;
    private javax.swing.JLabel l_UnitPrice;
    private javax.swing.JTextField txt_ProductName;
    private javax.swing.JTextField txt_Quantity;
    private javax.swing.JTextField txt_Total;
    private javax.swing.JTextField txt_UnitPrice;
    // End of variables declaration//GEN-END:variables
}
