/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package billing_system.applicationUIs;

/**
 *
 * @author Visitor
 */
public class CustomItemUnit extends javax.swing.JFrame {

    /**
     * Creates new form CustomItemUnit
     */
    public CustomItemUnit() {
        initComponents();

        jPanel1.removeAll();
        jPanel1.repaint();
        jPanel1.revalidate();

        jPanel1.add(pnlHasTheUnit);
        jPanel1.repaint();
        jPanel1.revalidate();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCustonItemUnit = new javax.swing.JPanel();
        lblCurrentUnit = new javax.swing.JLabel();
        checkUnitExists = new javax.swing.JCheckBox();
        lblCurrentUnit1 = new javax.swing.JLabel();
        txtCurrentUnit = new javax.swing.JTextField();
        ddChooseUnit = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        pnlHasNotTheUnit = new javax.swing.JPanel();
        lblUnitName = new javax.swing.JLabel();
        txtEnteredUnitRelation = new javax.swing.JTextField();
        ddRelationUnit = new javax.swing.JComboBox<>();
        txtUnitName = new javax.swing.JTextField();
        txtValue = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnCreateNewUnit = new javax.swing.JButton();
        pnlHasTheUnit = new javax.swing.JPanel();
        txtNewUnit = new javax.swing.JTextField();
        lblNewUnit = new javax.swing.JLabel();
        btnVerify = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        pnlCustonItemUnit.setBackground(new java.awt.Color(255, 255, 255));

        lblCurrentUnit.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblCurrentUnit.setText("Current Unit");

        checkUnitExists.setBackground(new java.awt.Color(255, 255, 255));
        checkUnitExists.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkUnitExists.setText("  Unit is not exist");
        checkUnitExists.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkUnitExistsMouseClicked(evt);
            }
        });

        lblCurrentUnit1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblCurrentUnit1.setText("Choose Unit");

        txtCurrentUnit.setEditable(false);
        txtCurrentUnit.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtCurrentUnit.setForeground(new java.awt.Color(102, 102, 102));
        txtCurrentUnit.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ddChooseUnit.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ddChooseUnit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "g", "mg" }));

        jPanel1.setLayout(new java.awt.CardLayout());

        lblUnitName.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblUnitName.setText("Unit Name");

        txtEnteredUnitRelation.setEditable(false);
        txtEnteredUnitRelation.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtEnteredUnitRelation.setForeground(new java.awt.Color(102, 102, 102));
        txtEnteredUnitRelation.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ddRelationUnit.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ddRelationUnit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "g", "mg" }));

        txtUnitName.setEditable(false);
        txtUnitName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtUnitName.setForeground(new java.awt.Color(102, 102, 102));
        txtUnitName.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtValue.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtValue.setForeground(new java.awt.Color(102, 102, 102));
        txtValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("=");

        btnCreateNewUnit.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnCreateNewUnit.setText("Create a New Unit");

        javax.swing.GroupLayout pnlHasNotTheUnitLayout = new javax.swing.GroupLayout(pnlHasNotTheUnit);
        pnlHasNotTheUnit.setLayout(pnlHasNotTheUnitLayout);
        pnlHasNotTheUnitLayout.setHorizontalGroup(
            pnlHasNotTheUnitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHasNotTheUnitLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(pnlHasNotTheUnitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHasNotTheUnitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(pnlHasNotTheUnitLayout.createSequentialGroup()
                            .addComponent(txtEnteredUnitRelation)
                            .addGap(0, 0, 0)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ddRelationUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlHasNotTheUnitLayout.createSequentialGroup()
                            .addComponent(lblUnitName, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(33, 33, 33)
                            .addComponent(txtUnitName, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnCreateNewUnit, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(36, 36, 36))
        );
        pnlHasNotTheUnitLayout.setVerticalGroup(
            pnlHasNotTheUnitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHasNotTheUnitLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlHasNotTheUnitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUnitName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUnitName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlHasNotTheUnitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ddRelationUnit)
                    .addComponent(txtEnteredUnitRelation, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCreateNewUnit)
                .addGap(8, 8, 8))
        );

        jPanel1.add(pnlHasNotTheUnit, "card3");

        txtNewUnit.setEditable(false);
        txtNewUnit.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtNewUnit.setForeground(new java.awt.Color(102, 102, 102));
        txtNewUnit.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblNewUnit.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblNewUnit.setText("New Unit");

        btnVerify.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnVerify.setText("Verify");

        javax.swing.GroupLayout pnlHasTheUnitLayout = new javax.swing.GroupLayout(pnlHasTheUnit);
        pnlHasTheUnit.setLayout(pnlHasTheUnitLayout);
        pnlHasTheUnitLayout.setHorizontalGroup(
            pnlHasTheUnitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHasTheUnitLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(pnlHasTheUnitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnVerify, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlHasTheUnitLayout.createSequentialGroup()
                        .addComponent(lblNewUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(txtNewUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
        );
        pnlHasTheUnitLayout.setVerticalGroup(
            pnlHasTheUnitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHasTheUnitLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlHasTheUnitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNewUnit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNewUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btnVerify)
                .addGap(26, 26, 26))
        );

        jPanel1.add(pnlHasTheUnit, "card2");

        javax.swing.GroupLayout pnlCustonItemUnitLayout = new javax.swing.GroupLayout(pnlCustonItemUnit);
        pnlCustonItemUnit.setLayout(pnlCustonItemUnitLayout);
        pnlCustonItemUnitLayout.setHorizontalGroup(
            pnlCustonItemUnitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCustonItemUnitLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pnlCustonItemUnitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCurrentUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCurrentUnit1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(pnlCustonItemUnitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ddChooseUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCurrentUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCustonItemUnitLayout.createSequentialGroup()
                .addGroup(pnlCustonItemUnitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlCustonItemUnitLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkUnitExists, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCustonItemUnitLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlCustonItemUnitLayout.setVerticalGroup(
            pnlCustonItemUnitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCustonItemUnitLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlCustonItemUnitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCurrentUnit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCurrentUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pnlCustonItemUnitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ddChooseUnit)
                    .addComponent(lblCurrentUnit1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(checkUnitExists, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCustonItemUnit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCustonItemUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int x = 0;

    private void checkUnitExistsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkUnitExistsMouseClicked
        if (x == 0) {
            jPanel1.removeAll();
            jPanel1.repaint();
            jPanel1.revalidate();

            jPanel1.add(pnlHasNotTheUnit);
            jPanel1.repaint();
            jPanel1.revalidate();
            x = 1;
        } else {
            jPanel1.removeAll();
            jPanel1.repaint();
            jPanel1.revalidate();

            jPanel1.add(pnlHasTheUnit);
            jPanel1.repaint();
            jPanel1.revalidate();
            x = 0;
        }
    }//GEN-LAST:event_checkUnitExistsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomItemUnit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomItemUnit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomItemUnit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomItemUnit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomItemUnit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateNewUnit;
    private javax.swing.JButton btnVerify;
    private javax.swing.JCheckBox checkUnitExists;
    private javax.swing.JComboBox<String> ddChooseUnit;
    private javax.swing.JComboBox<String> ddRelationUnit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCurrentUnit;
    private javax.swing.JLabel lblCurrentUnit1;
    private javax.swing.JLabel lblNewUnit;
    private javax.swing.JLabel lblUnitName;
    private javax.swing.JPanel pnlCustonItemUnit;
    private javax.swing.JPanel pnlHasNotTheUnit;
    private javax.swing.JPanel pnlHasTheUnit;
    private javax.swing.JTextField txtCurrentUnit;
    private javax.swing.JTextField txtEnteredUnitRelation;
    private javax.swing.JTextField txtNewUnit;
    private javax.swing.JTextField txtUnitName;
    private javax.swing.JTextField txtValue;
    // End of variables declaration//GEN-END:variables
}
