/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package billing_system.applicationUIs;

import javax.swing.JFrame;

/**
 *
 * @author ASHAN
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP_Main = new javax.swing.JPanel();
        L_SubTitle = new javax.swing.JLabel();
        L_Title = new javax.swing.JLabel();
        jP_Sub = new javax.swing.JPanel();
        btn_addDetails = new javax.swing.JButton();
        btn_viewDetails = new javax.swing.JButton();
        btn_updateDetails = new javax.swing.JButton();
        btn_deleteDetails = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_goodsDetails = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        L_SubTitle.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        L_SubTitle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        L_SubTitle.setText("Billing Management System");

        L_Title.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        L_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L_Title.setText("ABC Company (PVT) LTD.");

        btn_addDetails.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_addDetails.setText("Add Details");
        btn_addDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_addDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addDetailsActionPerformed(evt);
            }
        });

        btn_viewDetails.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_viewDetails.setText("View Details");
        btn_viewDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btn_updateDetails.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_updateDetails.setText("Update Details");
        btn_updateDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btn_deleteDetails.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_deleteDetails.setText("Delete Details");
        btn_deleteDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        t_goodsDetails.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        t_goodsDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(t_goodsDetails);

        javax.swing.GroupLayout jP_SubLayout = new javax.swing.GroupLayout(jP_Sub);
        jP_Sub.setLayout(jP_SubLayout);
        jP_SubLayout.setHorizontalGroup(
            jP_SubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_SubLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jP_SubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jP_SubLayout.createSequentialGroup()
                        .addComponent(btn_addDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_viewDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_updateDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_deleteDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jP_SubLayout.setVerticalGroup(
            jP_SubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_SubLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jP_SubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_addDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_viewDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_updateDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_deleteDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout jP_MainLayout = new javax.swing.GroupLayout(jP_Main);
        jP_Main.setLayout(jP_MainLayout);
        jP_MainLayout.setHorizontalGroup(
            jP_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_MainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_MainLayout.createSequentialGroup()
                        .addComponent(L_SubTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jP_Sub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jP_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jP_MainLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(L_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(919, Short.MAX_VALUE)))
        );
        jP_MainLayout.setVerticalGroup(
            jP_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_MainLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(L_SubTitle)
                .addGap(40, 40, 40)
                .addComponent(jP_Sub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jP_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jP_MainLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(L_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(633, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_Main, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addDetailsActionPerformed
        AddDetails addtl = new AddDetails();
        addtl.setVisible(true);
        addtl.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_btn_addDetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L_SubTitle;
    private javax.swing.JLabel L_Title;
    private javax.swing.JButton btn_addDetails;
    private javax.swing.JButton btn_deleteDetails;
    private javax.swing.JButton btn_updateDetails;
    private javax.swing.JButton btn_viewDetails;
    private javax.swing.JPanel jP_Main;
    private javax.swing.JPanel jP_Sub;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable t_goodsDetails;
    // End of variables declaration//GEN-END:variables
}
