/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package billing_system.applicationUIs;

import billing_system.dboperation.RegDBOperations;
import billing_system.models.RegDetails;
import javax.swing.JOptionPane;
import billing_system.applicationUIs.App;

public class UpdateBorrowers extends javax.swing.JFrame {

    RegDBOperations Regdbo = new RegDBOperations();
    String name;

    public UpdateBorrowers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblBorrowerCode = new javax.swing.JLabel();
        txtBorrowerCode = new javax.swing.JTextField();
        pnlImage = new javax.swing.JPanel();
        pnlPersonalDetails = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtNICNo = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        lblV = new javax.swing.JLabel();
        lblNICNo = new javax.swing.JLabel();
        ddGenger = new javax.swing.JComboBox<>();
        pnlContactDetails = new javax.swing.JPanel();
        lblMobile = new javax.swing.JLabel();
        lblTelephoneNo = new javax.swing.JLabel();
        txtTPMobile = new javax.swing.JTextField();
        txtTPLand = new javax.swing.JTextField();
        lblFixed = new javax.swing.JLabel();
        lblAdderess = new javax.swing.JLabel();
        txtAdderess = new javax.swing.JTextField();
        Update = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblBorrowerCode.setBackground(new java.awt.Color(255, 255, 255));
        lblBorrowerCode.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblBorrowerCode.setText("Borrower Code");

        txtBorrowerCode.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        javax.swing.GroupLayout pnlImageLayout = new javax.swing.GroupLayout(pnlImage);
        pnlImage.setLayout(pnlImageLayout);
        pnlImageLayout.setHorizontalGroup(
            pnlImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );
        pnlImageLayout.setVerticalGroup(
            pnlImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 241, Short.MAX_VALUE)
        );

        pnlPersonalDetails.setBackground(new java.awt.Color(249, 249, 249));
        pnlPersonalDetails.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personal Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 15))); // NOI18N

        lblName.setBackground(new java.awt.Color(255, 255, 255));
        lblName.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblName.setText("Name");

        txtName.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        txtNICNo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        lblGender.setBackground(new java.awt.Color(255, 255, 255));
        lblGender.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblGender.setText("Gender");

        lblV.setBackground(new java.awt.Color(255, 255, 255));
        lblV.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblV.setText("v");
        lblV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        lblNICNo.setBackground(new java.awt.Color(255, 255, 255));
        lblNICNo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblNICNo.setText("NIC No");

        ddGenger.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        ddGenger.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        javax.swing.GroupLayout pnlPersonalDetailsLayout = new javax.swing.GroupLayout(pnlPersonalDetails);
        pnlPersonalDetails.setLayout(pnlPersonalDetailsLayout);
        pnlPersonalDetailsLayout.setHorizontalGroup(
            pnlPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPersonalDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlPersonalDetailsLayout.createSequentialGroup()
                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPersonalDetailsLayout.createSequentialGroup()
                        .addComponent(lblNICNo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNICNo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lblV, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ddGenger, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        pnlPersonalDetailsLayout.setVerticalGroup(
            pnlPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPersonalDetailsLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNICNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNICNo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ddGenger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pnlPersonalDetailsLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblName, txtNICNo, txtName});

        pnlContactDetails.setBackground(new java.awt.Color(249, 249, 249));
        pnlContactDetails.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contact Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16))); // NOI18N

        lblMobile.setBackground(new java.awt.Color(255, 255, 255));
        lblMobile.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblMobile.setText("Mobile");

        lblTelephoneNo.setBackground(new java.awt.Color(255, 255, 255));
        lblTelephoneNo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblTelephoneNo.setText("Telephone No");

        txtTPMobile.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        txtTPLand.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        lblFixed.setBackground(new java.awt.Color(255, 255, 255));
        lblFixed.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblFixed.setText("Fixed");

        lblAdderess.setBackground(new java.awt.Color(255, 255, 255));
        lblAdderess.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblAdderess.setText("Adderess");

        txtAdderess.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        javax.swing.GroupLayout pnlContactDetailsLayout = new javax.swing.GroupLayout(pnlContactDetails);
        pnlContactDetails.setLayout(pnlContactDetailsLayout);
        pnlContactDetailsLayout.setHorizontalGroup(
            pnlContactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContactDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlContactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlContactDetailsLayout.createSequentialGroup()
                        .addComponent(lblTelephoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addGroup(pnlContactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTPMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(pnlContactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTPLand, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFixed, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlContactDetailsLayout.createSequentialGroup()
                        .addComponent(lblAdderess, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtAdderess)))
                .addContainerGap(284, Short.MAX_VALUE))
        );
        pnlContactDetailsLayout.setVerticalGroup(
            pnlContactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContactDetailsLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlContactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFixed, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(pnlContactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelephoneNo)
                    .addComponent(txtTPMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTPLand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlContactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdderess)
                    .addComponent(txtAdderess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        Update.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlPersonalDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblBorrowerCode, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBorrowerCode, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(78, 78, 78)
                        .addComponent(pnlImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlContactDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBorrowerCode, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBorrowerCode, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72)
                        .addComponent(pnlPersonalDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(pnlContactDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void loadUpdateBorrowerUI(RegDetails rd) {

        txtBorrowerCode.setText(rd.getBorrowerCode());
        txtName.setText(rd.getName());
        txtNICNo.setText(String.valueOf(rd.getNIC_Number()));
        ddGenger.setSelectedItem(rd.getGender());
        txtTPMobile.setText(String.valueOf(rd.getTP_Mobile()));
        txtTPLand.setText(String.valueOf(rd.getTP_Land()));
        txtAdderess.setText(rd.getAdderess());
        name = rd.getName();

    }

    void RegClear() {

        txtBorrowerCode.setText("");
        txtName.setText("");
        txtNICNo.setText("");
        ddGenger.setSelectedIndex(0);
        txtTPMobile.setText("");
        txtTPLand.setText("");
        txtAdderess.setText("");

    }

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        RegDetails rd = new RegDetails();

        if (!txtBorrowerCode.getText().equals("") && !txtName.getText().equals("")) {
            try {
                rd.setRegID(0);
                rd.setBorrowerCode(txtBorrowerCode.getText());
                rd.setName(txtName.getText());
                if (txtNICNo.getText().equals("")) {
                    rd.setNIC_Number(0);
                } else {
                    rd.setNIC_Number(Integer.parseInt(txtNICNo.getText()));
                }
                rd.setGender((String) ddGenger.getSelectedItem());
                if (txtTPMobile.getText().equals("")) {
                    rd.setTP_Mobile(0);
                } else {
                    rd.setTP_Mobile(Integer.parseInt(txtTPMobile.getText()));
                }
                if (txtTPLand.getText().equals("")) {
                    rd.setTP_Land(0);
                } else {
                    rd.setTP_Land(Integer.parseInt(txtTPLand.getText()));
                }
                if (txtAdderess.getText().equals("")) {
                    rd.setAdderess("Null");
                } else {
                    rd.setAdderess(txtAdderess.getText());
                }

                String msg = "<html>" + "Please Check all Details again...!<br><br>"
                        + "<tr><td>Borrower code</td>-<td> </td><td> " + txtBorrowerCode.getText() + "</td></tr>"
                        + "<tr><td>Name </td>-<td></td><td> " + txtName.getText() + "</td></tr>"
                        + "<tr><td>NIC Number</td>-<td></td><td> " + txtNICNo.getText() + "</td></tr>"
                        + "<tr><td>Gender</td>-<td></td><td>" + ddGenger.getSelectedItem() + "</td></tr>"
                        + "<tr><td>Mobile</td>-<td></td><td>" + txtTPMobile.getText() + "</td></tr>"
                        + "<tr><td>Fixed</td>-<td></td><td>" + txtTPLand.getText() + "</td></tr>"
                        + "<tr><td>Adderess</td>-<td></td><td>" + txtAdderess.getText() + "</td></tr><br><br>" + "Save Changes" + "</html>";

                int p = JOptionPane.showConfirmDialog(this, msg, "Update Details", JOptionPane.YES_NO_OPTION);

                int result = 0;
                if (p == 0) {
                    result = Regdbo.UpdateBorrowerDetails(rd, name);
                    App a = new App();
                    a.LoadBorrorwerTbl();
                    UpdateDeleteBorrowers udb = new UpdateDeleteBorrowers();
                    udb.LoadBorrorwerTbl();
                }
                switch (result) {
                    case 1:
                        dispose();
                        break;
                    case 2:
                        JOptionPane.showMessageDialog(this, "Error Occured While Inserting ,Please Reenter Details!");
                        RegClear();
                }
            } catch (Exception e) {
                System.out.println("btnAddDetails --> " + e);
                JOptionPane.showMessageDialog(this, "Error Occured, Check Your Details Again");
            }
        } else {
            JOptionPane.showMessageDialog(this, "You must enter Name and Borrower Code");
        }
    }//GEN-LAST:event_UpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateBorrowers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateBorrowers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateBorrowers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateBorrowers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateBorrowers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Update;
    private javax.swing.JComboBox<String> ddGenger;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAdderess;
    private javax.swing.JLabel lblBorrowerCode;
    private javax.swing.JLabel lblFixed;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblMobile;
    private javax.swing.JLabel lblNICNo;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTelephoneNo;
    private javax.swing.JLabel lblV;
    private javax.swing.JPanel pnlContactDetails;
    private javax.swing.JPanel pnlImage;
    private javax.swing.JPanel pnlPersonalDetails;
    private javax.swing.JTextField txtAdderess;
    private javax.swing.JTextField txtBorrowerCode;
    private javax.swing.JTextField txtNICNo;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtTPLand;
    private javax.swing.JTextField txtTPMobile;
    // End of variables declaration//GEN-END:variables
}
